name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.context.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        context:
          - runs-on: windows-2022
            rid: win-x64
          - runs-on: windows-2022
            rid: win-arm64
          - runs-on: ubuntu-22.04
            rid: linux-x64
          - runs-on: ubuntu-22.04
            rid: linux-arm64
          - runs-on: macos-15
            rid: osx-x64
          - runs-on: macos-15
            rid: osx-arm64
    timeout-minutes: 2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        id: setup-dotnet
        uses: actions/setup-dotnet@v4

      - name: Build & Pack Project
        id: build
        run: dotnet publish -c Release --sc false -r ${{ matrix.context.rid }}

      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: Binaries (${{ matrix.context.rid }})
          path: |
            src/Savepatch/bin/Release/net8.0/${{ matrix.context.rid }}/publish/**/*
